### ISSUE TITLE
UI Update

### ISSUE THREAD

**Issue by andrewmfraser** [FraserCoyle/sermon-manager-issues#33]
- [ ] Ensure all applications are using the same Frontend Framework (Bootstrap)
- [ ] Change Menu structure to the following:
    * {Church Name}
        * Getting Started (only appears when you're getting started)
        * Analytics
        * Sermons
        * Series
        * Speakers
        * Topics
        * Files
        * Help
    * Settings
        * Account
        * Service Times
        * Custom Domain
        * iTunes
        * Design
        * Subscription
        * Users
- [ ] Add Church Name somewhere on page - link to sm-frontend
- [ ] Allow switching of churches from the menu
- [ ] Add link to Front End from Dashboard - #31 
- [ ] Move Delete button into new actions section
- [ ] Add Publish/Unpublish button to new actions section - #61
- [ ] Have a modal to confirm deleting a sermon - #9 
- [ ] Change colours to provide more contrast for form elements - #60

**Comment by andrewmfraser** [comment]
Superseded by #119
